{%set name = "chartkick" %}
{%set version = "0.5.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "1cc0306b4a6de1e33ed8a849e077e4ed517c0bd4fca05e2a286c46585e89a52b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - chartkick
    - chartkick.templatetags

about:
  home: https://github.com/mher/chartkick.py
  license: MIT
  summary: 'Create beautiful Javascript charts with minimal code'

extra:
  recipe-maintainers:
    - pmlandwehr
