{% set name = "chartkick" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cc0306b4a6de1e33ed8a849e077e4ed517c0bd4fca05e2a286c46585e89a52b

build:
  number: 1002
  script: pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - chartkick
    - chartkick.templatetags

about:
  home: https://github.com/mher/chartkick.py
  license: MIT
  summary: 'Create beautiful Javascript charts with minimal code'

extra:
  recipe-maintainers:
    - pmlandwehr
