appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: BmNR1cL6/FwdZO0TVSMMojiKRMJjnmfNPriwW44GVJUEAS9ZZK84sUCYijAM+Y4msuJnehqe65qaT6BC08GChP+GHGXvD1LBWir509ejrcMRE3J3GqXrCOJcGb1LeIT5RDODzwKv6A3umyJmd39oEdBchu+hupfe76rGZu0tsjWc+6VVHRDV+jZHdxcnI+Dk5+rB4i++g3gJhH3ezy2RyuoCc/psa1k7aLl46GaiqH9waG5kOUK90hTSwKN5IBmELMnF6KhDhMp7sGjGv0B6ZiymvvgWMpKASzlw+OuR0kbTyPDPz3+nxrw8Sy6jIwix7Na/GcfeydU4F2ivo0oJjIpCvwgao5hZSdDWRZ8evPGzFrsVtxYh759zaNYKiTVOpSFdlQJ8dEbrCclQ+RLR1NbhGgdwzC5/4OfZzZieerzf/JKw30zzbqb8MnsuKIekMnR61on4hIfiy96jgZ/rpLZ65QDiJ0EzKdEZ2rak7QNBUkdcXpx+e4Bn4HECHCj9apsmq25604bsOF8qQmhkan611u4Bm6Sv80UzC4s62qwee6U8T3xwhdO8TRBFeV3VN9ES11F+ZPE0oX0aVHj1zKOPWyFOIRZaMfs20JLZjKJOzFLtHz4J6RQ594VexMJO9df3+Mhq1e4eEAjV1Johk53wYyhNyjv/tD7/qHtxbn8=}
provider:
  win: azure
conda_forge_output_validation: true
